#!/bin/bash

if [ $# -eq 0 ];
then
  echo usage $0 files ...
  exit 1
fi

for file in $*;
do
	echo "# Processing: $file" 1>&2
	if [ ! -f "$file" ];
		then
			echo Not a file: "$file" 1>&2
			continue
	fi
	TYPE=`file - < "$file" | cut -d: -f2`
	if echo "$TYPE" | grep -q '(with BOM)';
		then
			( mv "${file}" "${file}.with_BOM" \
				&& uconv -f utf-8 -t utf-8 --remove-signature\
					< "${file}.with_BOM" \
					> "${file}" )\
				|| ( echo Error processing "$file" 1>&2 ; 
				exit 1)
			rm "${file}.with_BOM"
			
		else
			echo "# $file already without BOM, skipping." 1>&2
	fi
done
